= `WHERE visible` + `cron` job vs `WHERE current_timestamp < expired_at`

This project is created because there are creative engineers believe that having an indexed boolean column with cron jobs integration is better than pure SQL queries.

For example of filtering expired posts in a database, instead of querying by `SELECT * FROM posts WHERE current_timestamp < expired_at`.
They tend to create an extra boolean column named `visible`, query by `SELECT * FROM posts WHERE visible`, and create another cron job to synchronize the `visible` column with `expired_at` periodically.

== TLDR

. With 10,000,000 rows, the difference between the 2 are less then 1ms.
. By using boolean column and cron job, we gain little benefit (by few milliseconds) but increase the difficulty of maintainability.

== Benchmark

[%autowidth]
|===
| Query                                                       | Execution Time (ms)

| `SELECT * FROM posts WHERE visible`                         | 7.959537
| `SELECT * FROM posts WHERE current_timestamp < expired_at`  | 8.10381
|===

Database Version::
  PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
Number of rows:: 10,000,000
Iterations:: 1,000
DB Schema::
+
[source,sql]
----
CREATE TABLE posts (
  id SERIAL PRIMARY KEY NOT NULL,
  expired_at timestamp without time zone,
  visible boolean DEFAULT false
);
CREATE INDEX index_posts_on_expired_at ON posts USING btree (expired_at);
CREATE INDEX index_posts_on_visible ON posts USING btree (visible);
----

== Usage

. start DB server in a docker container named `pg`:
+
[source,shell]
----
bin/populate >initdb.d/data.csv &&
  docker run --rm \
    -e POSTGRES_PASSWORD=password \
    -v $(pwd)/initdb.d:/docker-entrypoint-initdb.d \
    -v $(pwd):/src \
    -w /src \
    --name pg postgres:13.4-alpine
----
. Run scripts in `pg` container:
+
[source,shell]
----
docker exec -it pg psql -U postgres -c 'EXPLAIN ANALYZE SELECT * FROM posts WHERE visible;'
----
+
Or print average execution time by `bin/execution_time` with 1000 iterations:
+
[source,shell]
----
docker exec -i pg sh <<SCRIPT
apk add ruby ruby-json jq &&
  bin/executaion_time 'SELECT * FROM posts WHERE visible' 1000
SCRIPT
----

